name: psmc-python
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.6
  - numba=0.56.4
  - numpy=1.23.1
  - numpy-base=1.23.1
  - pandas=1.4.3
  - python=3.10.4
  - scipy=1.10.0
  - tqdm=4.64.0
  - pip=22.3.1
  - pip:
    - basemap==1.3.6
    - basemap-data==1.3.2
    - line-profiler==4.0.3